[package]
name = "muninn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
tokio = { version = "1.5", features = ["full", "test-util"] }
async-trait = "0.1.68"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.11.6"
rayon = "1.10.0"
fastembed = "3.7.0"
uuid = { version = "1.7.0", features = ["v4"] }
dirs = "5.0.1"
chrono = "0.4.19"
tracing = "0.1"
tracing-subscriber = "0.3.18"
actix = "0.13.3"
futures = "0.3.30"
rumqttc = "0.24.0"
rmp-serde = "1.1.2"
sha2 = "0.10.8"
anyhow = "1.0.81"
