version: '3'
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    restart: always
  scrapper:
    image: amerkurev/scrapper:latest
    container_name: scrapper
    ports:
      - "3000:3000"

  jaeger:
      image: jaegertracing/all-in-one:1.45
      container_name: jaeger
      ports:
        - "5775:5775/udp"     # UDP port for the agent
        - "6831:6831/udp"     # UDP port for the agent
        - "6832:6832/udp"     # UDP port for the agent
        - "5778:5778"         # UI and query monitoring
        - "16686:16686"       # Web UI
        - "14268:14268"       # HTTP collector
        - "14250:14250"       # GRPC
        - "9411:9411"         # Zipkin compatibility
