version: "3.7"
services:
  muninn:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./data/messages/:/root/.local/share/muninn:rw
  #docker run -p 8001:8000 chromadb/chroma
  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    restart: always
